apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.kongig.name }}
  namespace: {{ .Values.kongig.namespaceapp }}
spec:
  project: {{ .Values.kongig.project }}
  source:
    chart: {{ .Values.kongig.chart }}
    repoURL: {{ .Values.kongig.repo }}
    targetRevision: {{ .Values.kongig.targetrevision }}
    helm:
      values: |-
        proxy:
          enabled: false
  destination:
    server: {{ .Values.kongig.server }}
    namespace: {{ .Values.kongig.namespacedest }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.traefikig.name }}
  namespace: {{ .Values.traefikig.namespaceapp }}
spec:
  project: {{ .Values.traefikig.project }}
  source:
    chart: {{ .Values.traefikig.chart }}
    repoURL: {{ .Values.traefikig.repo }}
    targetRevision: {{ .Values.traefikig.targetrevision }}
    helm:
      values: |-
        service:
          enabled: false
        providers:
          ingressClass: traefik
  destination:
    server: {{ .Values.traefikig.server }}
    namespace: {{ .Values.traefikig.namespacedest }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
