apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  {{- if .Values.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.pgadmin.path }}
            pathType: {{ .Values.pgadmin.pathType }}
            backend:
              serviceName: {{ .Values.pgadmin.name }}-svc
              servicePort: {{ .Values.pgadmin.servicePort }}

          - path: {{ .Values.echoserver.path }}
            pathType: {{ .Values.echoserver.pathType }}
            backend:
              serviceName: {{ .Values.echoserver.name }}-svc
              servicePort: {{ .Values.echoserver.servicePort }}

          - path: {{ .Values.helloworld.path }}
            pathType: {{ .Values.helloworld.pathType }}
            backend:
              serviceName: {{ .Values.helloworld.name }}-svc
              servicePort: {{ .Values.helloworld.servicePort }}

---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: kong-ingress
#   annotations:
#     kubernetes.io/ingress.class: "kong"
#     konghq.com/strip-path: "true"
# spec:
#   rules:
#     - host: nlb-new02-b800bc45a781f86d.elb.ap-southeast-1.amazonaws.com
#       http:
#         paths:
#           - path: /kongecho
#             pathType: Prefix
#             backend:
#               service:
#                 name: echoserver-svc
#                 port:
#                   number: 80
#           - path: /konghello
#             pathType: Prefix
#             backend:
#               service:
#                 name: helloworld-svc
#                 port:
#                   number: 80

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: traefik-ingress
#   annotations:
#     kubernetes.io/ingress.class: "traefik"
# spec:
#   rules:
#     - host: nlb-new02-b800bc45a781f86d.elb.ap-southeast-1.amazonaws.com
#       http:
#         paths:
#           - path: /traefikecho
#             pathType: Prefix
#             backend:
#               service:
#                 name: echoserver-svc
#                 port:
#                   number: 80
#           - path: /traefikhello
#             pathType: Prefix
#             backend:
#               service:
#                 name: helloworld-svc
#                 port:
#                   number: 80
