apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pgadmin.name }}
  labels:
    app: {{ .Values.pgadmin.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.pgadmin.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.pgadmin.name }}
    spec:
      containers:
        - name: {{ .Values.pgadmin.name }}
          image: {{ .Values.pgadmin.image }}
          env:
            - name: PGADMIN_DEFAULT_PASSWORD
              value: {{ .Values.pgadmin.password }}
            - name: PGADMIN_DEFAULT_EMAIL
              value: {{ .Values.pgadmin.email }}
            - name: SCRIPT_NAME 
              value: {{ .Values.pgadmin.scriptname }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgadmin.name }}-svc
  labels:
    app: {{ .Values.pgadmin.name }}
spec:
  type: {{ .Values.pgadmin.serviceType }}
  ports:
    - port: {{ .Values.pgadmin.servicePort }}
  selector:
    app: {{ .Values.pgadmin.name }}
    
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: pgadmin-config
data:
 servers.json: |
   {
       "Servers": {
         "1": {
           "Name": "newpgdb",
           "Group": "Servers",
           "Port": 5432,
           "Username": "postgres",
           "Host": "newpgdb.cnae1m6nnifz.ap-southeast-1.rds.amazonaws.com",
           "SSLMode": "prefer",
           "MaintenanceDB": "postgres"
         }
       }
   }