apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.traefik }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.pgadmin.traefik_path }}
            pathType: {{ .Values.pgadmin.pathType }}
            backend:
              service:
                name: {{ .Values.pgadmin.name }}-svc
                port: 
                  number: {{ .Values.pgadmin.servicePort }}
