# echoserver:
#   name: echoserver
#   image: ealen/echo-server:latest
#   replicas: 1
#   containerPort: 80
#   serviceType: ClusterIP
#   servicePort: 80
#   kong_path: /kongecho
#   traefik_path: /traefikecho
#   pathType: Exact
# helloworld:
#   name: helloserver
#   image: tutum/hello-world:latest
#   replicas: 1
#   containerPort: 80
#   serviceType: ClusterIP
#   servicePort: 80
#   kong_path: /konghello
#   traefik_path: /traefikhello
#   pathType: Exact
# pgadmin:
#   kong: kongpgadmin
#   traefik: traefikpgadmin
#   image: dpage/pgadmin4
#   replicas: 1
#   containerPort: 80
#   serviceType: ClusterIP
#   servicePort: 80
#   kong_path: /kongpgadmin
#   traefik_path: /traefikpgadmin
#   pathType: Prefix
#   email: patiphan.t@appman.co.th
#   password: admin
#   kongscriptname: /kongpgadmin
#   traefikscriptname: /traefikpgadmin
# ingress:
#   kong: kong-ingress
#   traefik: traefik-ingress
#   host: nlb-new02-241016c8753432ae.elb.ap-southeast-1.amazonaws.com
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.org/rewrites: "serviceName=echoserver-svc rewrite=/"
#     nginx.org/rewrites: "serviceName=helloworld-svc rewrite=/"
# nginxig:
#   name: nginx-ingress
#   namespaceapp: argocd
#   namespacedest: nginx-ingress
#   project: default
#   chart: nginx-ingress
#   repo: https://helm.nginx.com/stable
#   targetrevision: 0.4.1
#   server: https://kubernetes.default.svc
# kongig:
#   name: kong-ingress-controller
#   namespaceapp: argocd
#   namespacedest: kong
#   project: default
#   chart: kong
#   repo: https://charts.konghq.com
#   targetrevision: 2.7.0
#   server: https://kubernetes.default.svc
# traefikig:
#   name: traefik-ingress-controller
#   namespaceapp: argocd
#   namespacedest: traefik
#   project: default
#   chart: traefik
#   repo: https://helm.traefik.io/traefik
#   targetrevision: 10.15.0
#   server: https://kubernetes.default.svc
# nginxnp:
#   name: nginx-nodeport
#   namespace: nginx-ingress
#   type: NodePort
#   porthttp: 80
#   porthttps: 443
#   tghttp: 80
#   tghttps: 443
#   protocal: TCP
#   http: http
#   nodeport: 32593
#   https: https
#   app: nginx-ingress-nginx-ingress
# kongnp:
#   name: kong
#   namespace: kong
#   type: NodePort
#   porthttp: 80
#   porthttps: 443
#   tghttp: 8000
#   tghttps: 8443
#   protocal: TCP
#   nodeport: 32592
#   http: http
#   https: https
#   app: kong
# traefiknp:
#   name: traefik
#   namespace: traefik
#   type: NodePort
#   porthttp: 80
#   porthttps: 443
#   tghttp: 8000
#   tghttps: 8443
#   protocal: TCP
#   nodeport: 32591
#   http: http
#   https: https
#   app: traefik
