echoserver:
  name: echoserver
  image: ealen/echo-server:latest
  replicas: 1
  containerPort: 80
  serviceType: ClusterIP
  servicePort: 80
  path: /echo
  pathType: Exact
helloworld:
  name: helloworld
  image: tutum/hello-world:latest
  replicas: 1
  containerPort: 80
  serviceType: ClusterIP
  servicePort: 80
  path: /hello
  pathType: Exact
ingress:
  host: a15a235b3cbc24e049a07f419dd365fc-8579903.ap-southeast-1.elb.amazonaws.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/rewrites: "serviceName=echoserver-svc rewrite=/"
    nginx.org/rewrites: "serviceName=helloworld-svc rewrite=/"